export default [
  // Projects looking for funding
  {
    _id: 'sample-1',
    title: 'Solar Water Pumps for Rural Farms',
    description: 'Install solar-powered water pumps to increase irrigation and reduce diesel use.',
    goal: 5000,
    collected: 1200,
    owner: { username: 'Amina', avatar: null, region: 'Nairobi' },
    images: [],
    status: 'funding',
  },
  {
    _id: 'sample-2',
    title: 'Community Tree Planting',
    description: 'Support community reforestation and agroforestry to restore degraded land.',
    goal: 2000,
    collected: 800,
    owner: { username: 'Joseph', avatar: null, region: 'Kisumu' },
    images: [],
    status: 'funding',
  },
  {
    _id: 'sample-3',
    title: 'Clean Cookstoves Initiative',
    description: 'Provide efficient cookstoves to reduce indoor air pollution and fuel use.',
    goal: 3000,
    collected: 150,
    owner: { username: 'Grace', avatar: null, region: 'Mombasa' },
    images: [],
    status: 'funding',
  },
  // Finished projects
  {
    _id: 'finished-1',
    title: 'Rainwater Harvesting for Schools',
    description: 'Installed rainwater collection systems in 10 rural schools.',
    goal: 4000,
    collected: 4000,
    owner: { username: 'Samuel', avatar: null, region: 'Eldoret' },
    images: [],
    status: 'finished',
  },
  {
    _id: 'finished-2',
    title: 'Urban Green Spaces',
    description: 'Transformed vacant lots into community gardens and parks.',
    goal: 6000,
    collected: 6000,
    owner: { username: 'Lilian', avatar: null, region: 'Nakuru' },
    images: [],
    status: 'finished',
  },
  {
    _id: 'finished-3',
    title: 'Plastic Recycling Drive',
    description: 'Collected and recycled 5 tons of plastic waste.',
    goal: 2500,
    collected: 2500,
    owner: { username: 'Brian', avatar: null, region: 'Kampala' },
    images: [],
    status: 'finished',
  },
  {
    _id: 'finished-4',
    title: 'Biogas for Villages',
    description: 'Installed biogas digesters for 50 households.',
    goal: 7000,
    collected: 7000,
    owner: { username: 'Esther', avatar: null, region: 'Machakos' },
    images: [],
    status: 'finished',
  },
  {
    _id: 'finished-5',
    title: 'Mangrove Restoration',
    description: 'Restored 20 hectares of mangrove forest along the coast.',
    goal: 8000,
    collected: 8000,
    owner: { username: 'David', avatar: null, region: 'Lamu' },
    images: [],
    status: 'finished',
  },
]
